ARG BASE=debian:latest

FROM ${BASE}

ARG AUTHOR
ARG VERSION
LABEL maintainer=${AUTHOR} version=${VERSION}

RUN apt-get update && \
  apt-get install -y bash ca-certificates tzdata curl && \
  cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  update-ca-certificates && \
  echo "Asia/Shanghai" > /etc/timezone