ARG BASE=caddy:2-alpine

FROM ${BASE}

USER root

ARG AUTHOR
ARG VERSION
LABEL maintainer=${AUTHOR} version=${VERSION}

ENV TZ=Asia/Shanghai

COPY ./ssl/beagle-ca.crt /usr/local/share/ca-certificates/beagle-ca.crt

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
    apk --no-cache --update add ca-certificates tzdata curl && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    update-ca-certificates
