apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: facefusion-pvc
  labels:
    app: facefusion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facefusion
  labels:
    app: facefusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facefusion
  template:
    metadata:
      labels:
        app: facefusion
    spec:
      containers:
        - name: facefusion
          image: registry.cn-qingdao.aliyuncs.com/wod/verdantflare-app:facefusion-3.7.1
          imagePullPolicy: IfNotPresent
          command: ["python", "facefusion.py"]
          args: ["run", "--execution-providers", "cuda"]
          ports:
            - name: http
              containerPort: 7860
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: data
              mountPath: /facefusion/.assets
              subPath: assets
            - name: data
              mountPath: /facefusion/.caches
              subPath: caches
            - name: data
              mountPath: /facefusion/.jobs
              subPath: jobs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: facefusion-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: facefusion
  labels:
    app: facefusion
spec:
  type: ClusterIP
  selector:
    app: facefusion
  ports:
    - name: http
      port: 7870
      targetPort: http
