ARG BASE=weishaw/sub2api:latest

FROM ${BASE}

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=latest
LABEL maintainer=${AUTHOR} version=${VERSION}

ENV TZ=Asia/Shanghai \
    TIMEZONE=Asia/Shanghai

RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone
