apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-pvc
  namespace: default
  labels:
    app: comfyui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # storageClassName: "your-storage-class" # 如果集群有默认 StorageClass 可忽略，否则请指定