ARG BASE=mysql:8.4.9
FROM $BASE

ARG AUTHOR=mengkzhaoyun@gmail.com
ARG VERSION=8.4.9
LABEL maintainer=$AUTHOR version=$VERSION

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
