name: comfyui

on:
  push:
    branches:
      - comfyui
  workflow_dispatch:

env:
  BUILD_VERSION: "v0.21.1"
  CUDA_VERSION: "13.2.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./comfyui
          file: ./comfyui/dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          build-args: |
            CUDA_VERSION=${{ env.CUDA_VERSION }}
            COMFYUI_VERSION=${{ env.BUILD_VERSION }}
          tags: registry.cn-qingdao.aliyuncs.com/wod/comfyui:${{ env.BUILD_VERSION }}-cu${{ env.CUDA_VERSION }}

      - name: Image build success
        run: echo "comfyui:${{ env.BUILD_VERSION }} built and pushed successfully!"
