name: headscale

on:
  push:
    branches:
      - headscale

env:
  BUILD_VERSION: v0.27.1
  SOURCE_IMAGE: headscale/headscale

jobs:
  sync-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push AMD64 image
        run: |
          docker pull --platform linux/amd64 ${{ env.SOURCE_IMAGE }}:${{ env.BUILD_VERSION }}
          docker tag ${{ env.SOURCE_IMAGE }}:${{ env.BUILD_VERSION }} registry.cn-qingdao.aliyuncs.com/wod/headscale:${{ env.BUILD_VERSION }}-amd64
          docker tag ${{ env.SOURCE_IMAGE }}:${{ env.BUILD_VERSION }} ghcr.io/${{ github.repository_owner }}/headscale:${{ env.BUILD_VERSION }}-amd64
          docker push registry.cn-qingdao.aliyuncs.com/wod/headscale:${{ env.BUILD_VERSION }}-amd64
          docker push ghcr.io/${{ github.repository_owner }}/headscale:${{ env.BUILD_VERSION }}-amd64

      - name: Pull and push ARM64 image
        run: |
          docker pull --platform linux/arm64 ${{ env.SOURCE_IMAGE }}:${{ env.BUILD_VERSION }}
          docker tag ${{ env.SOURCE_IMAGE }}:${{ env.BUILD_VERSION }} registry.cn-qingdao.aliyuncs.com/wod/headscale:${{ env.BUILD_VERSION }}-arm64
          docker tag ${{ env.SOURCE_IMAGE }}:${{ env.BUILD_VERSION }} ghcr.io/${{ github.repository_owner }}/headscale:${{ env.BUILD_VERSION }}-arm64
          docker push registry.cn-qingdao.aliyuncs.com/wod/headscale:${{ env.BUILD_VERSION }}-arm64
          docker push ghcr.io/${{ github.repository_owner }}/headscale:${{ env.BUILD_VERSION }}-arm64

      - name: Create and push manifest (Aliyun)
        run: |
          docker buildx imagetools create \
            --tag registry.cn-qingdao.aliyuncs.com/wod/headscale:${{ env.BUILD_VERSION }} \
            registry.cn-qingdao.aliyuncs.com/wod/headscale:${{ env.BUILD_VERSION }}-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/headscale:${{ env.BUILD_VERSION }}-arm64

      - name: Create and push manifest (GHCR)
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository_owner }}/headscale:${{ env.BUILD_VERSION }} \
            ghcr.io/${{ github.repository_owner }}/headscale:${{ env.BUILD_VERSION }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/headscale:${{ env.BUILD_VERSION }}-arm64

      - name: Image sync success
        run: echo "headscale:${{ env.BUILD_VERSION }} synced to Aliyun and GHCR successfully!"
