name: Nginx

on:
  push:
    branches:
      - nginx-*

jobs:
  nginx-1.27:
    if: github.ref == 'refs/heads/nginx-1.27'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push Docker image for AMD64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.bealge/alpine.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-amd64
          platforms: linux/amd64
          build-args: |
            BASE=nginx:1.27.4-alpine
            AUTHOR=${{ github.repository_owner }}
            VERSION=1.27.4

      - name: Build and push Docker image for ARM64
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.bealge/alpine.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-arm64
          platforms: linux/arm64
          build-args: |
            BASE=nginx:1.27.4-alpine
            AUTHOR=${{ github.repository_owner }}
            VERSION=1.27.4
          
      - name: Create and push manifest
        run: |
          docker manifest create registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-arm64
          docker manifest annotate registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-amd64 --os linux --arch amd64
          docker manifest annotate registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-arm64 --os linux --arch arm64
          docker manifest push registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine
          
      - name: Create and push additional manifests
        run: |
          docker manifest create registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-arm64
          docker manifest annotate registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-amd64 --os linux --arch amd64
          docker manifest annotate registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-arm64 --os linux --arch arm64
          docker manifest push registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4
          
          docker manifest create registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-arm64
          docker manifest annotate registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-amd64 --os linux --arch amd64
          docker manifest annotate registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27 \
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-arm64 --os linux --arch arm64
          docker manifest push registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27

      - name: Image push success
        run: echo "Docker images and manifests pushed successfully to registry.cn-qingdao.aliyuncs.com/wod/nginx"
