name: Nginx

on:
  push:
    branches:
      - nginx-*

jobs:
  nginx127:
    if: github.ref == 'refs/heads/nginx-1.27'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          # 启用 buildx 缓存导出功能
          driver-opts: |
            image=moby/buildkit:master
            network=host

      # 设置缓存
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      # 构建所有架构镜像，但分别输出不同标签
      - name: Build and push all Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./.bealge/alpine.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4
            registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE=nginx:1.27.4-alpine
            AUTHOR=${{ github.repository_owner }}
            VERSION=1.27.4
          # 使用缓存
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          # 输出单架构镜像
          outputs: |
            type=registry,name=registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-amd64,platform=linux/amd64
            type=registry,name=registry.cn-qingdao.aliyuncs.com/wod/nginx:1.27.4-alpine-arm64,platform=linux/arm64
            type=registry

      # 更新缓存
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image push success
        run: echo "Docker images and manifests pushed successfully to registry.cn-qingdao.aliyuncs.com/wod/nginx"
